Ansible 4
Otus-DevOps-2022-02/ravaevay_infra pull request #12
Opened 2022-05-25 01:05 UTC by ravaevay

# Выполнено ДЗ №11

 - [+ ] Основное ДЗ
 - [ +-] Задание со *

## В процессе сделано:
 Задание №11

 - Установлен Vagrant и провайдер vmware_esxi (поскольку задания выполняются на VM и хотелось попробовать провайдера более приближенного к прод среде). Обкатан процесс создания VM и применнения сценариев ansible. В конфигурацию Vagrantfile добавлена extar_vars для настройки Nginx на 80 порту.
 - Протестирована связка Molecule c провайдером vmware:
      molecule init -r db -d vmware default

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-05-26 13:51 UTC, mrgreyves requested changes
Прочитайте мой комментарий =)

2022-05-26 13:51 UTC, mrgreyves commented on ansible/roles/db/tasks/install_mongo.yml
> +  - name: Add an Apt signing key, uses whichever key is at the URL
Вот тут проблемки
Попробуйте поправить форматирование и перезапустить тесты

2022-05-27 05:41 UTC, ravaevay commented on ansible/roles/db/tasks/install_mongo.yml
> +  - name: Add an Apt signing key, uses whichever key is at the URL
исправил)

2022-05-27 08:17 UTC, mrgreyves approved these changes
Вот теперь апрув =)

2022-05-29 06:43 UTC, merged